#==============================================#
# Car Trap by RedSMURF: Configuration file #
#==============================================#

# To add a new Car Trap, follow the example below
# [CarTrap Name]
# CAR_FLAGS                    = a - Shake
# CAR_TEAM                     = 0 - None             1 - Terrorist           2 - Counter-Terrorist      3 - Both

# CAR_FALL_STRENGTH            = Strength of the Car Trap's fall (higher value = faster fall)
# CAR_FALL_FREQ                = Frequency of the Car Trap's fall (lower value = more frequent falls)
# CAR_IDLE_DURATION            = Duration of the idle state in seconds
# CAR_RAISE_STRENGTH           = Strength of the Car Trap's raise (higher value = faster raise)
# CAR_COOLDOWN                 = Cooldown in seconds before the Car Trap can be activated again
# CAR_SHAKE_DISTANCE           = Distance in units for the shake effect
# CAR_SHAKE_AMPLITUDE          = Amplitude of the shake effect
# CAR_SHAKE_FREQUENCY          = Frequency of the shake effect
# CAR_SHAKE_DURATION           = Duration of the shake effect in seconds
# CAR_SOUND_ROPE               = Sound played for the rope
# CAR_SOUND_SWITCH             = Sound played for the switch
# CAR_SOUND_SMASH              = Sound played for the smash effect

# To make a Car Trap available in the menu, you must defined at least it's name like this [RedSMURF's Car Trap]
# Car Trap model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_SOUND_ROPE          = CarTrap/cartrap_rope1.wav
SETTING_DEFAULT_SOUND_ROPE          = CarTrap/cartrap_rope2.wav
SETTING_DEFAULT_SOUND_ROPE          = CarTrap/cartrap_rope3.wav
SETTING_DEFAULT_SOUND_SWITCH        = buttons/lever4.wav
SETTING_DEFAULT_SOUND_SMASH         = CarTrap/cartrap_explode_impact1.wav
SETTING_DEFAULT_SOUND_SMASH         = CarTrap/cartrap_explode_impact2.wav
SETTING_DEFAULT_FLAGS               = a
SETTING_DEFAULT_TEAM                = 3
SETTING_DEFAULT_FRAMERATE           = 2.0
SETTING_DEFAULT_FALL_STRENGTH       = 125.0 125.0
SETTING_DEFAULT_FALL_FREQ           = 0.1 0.1
SETTING_DEFAULT_IDLE_DURATION       = 1.9 2.2
SETTING_DEFAULT_RAISE_STRENGTH      = 120.0 120.0
SETTING_DEFAULT_COOLDOWN            = 2.0 3.0
SETTING_DEFAULT_SHAKE_DISTANCE      = 500.0
SETTING_DEFAULT_SHAKE_AMPLITUDE     = 8
SETTING_DEFAULT_SHAKE_FREQUENCY     = 1
SETTING_DEFAULT_SHAKE_DURATION      = 2
SETTING_KILL_WORLD                  = 0

SETTING_MODEL_ROPE                  = models/CarTrap/rope.mdl
SETTING_MODEL_SWITCH                = models/CarTrap/switch.mdl
SETTING_MODEL_CAR_1                 = models/CarTrap/car002a.mdl
SETTING_MODEL_CAR_2                 = models/CarTrap/car003a.mdl
SETTING_MODEL_CAR_3                 = models/CarTrap/car004a.mdl
SETTING_MINS_SWITCH                 = -7.86 -11.74 -17.89
SETTING_MAXS_SWITCH                 = 10.96 11.74 17.89
SETTING_MINS_CAR_1                  = -79.22 -37.56 -23.78
SETTING_MAXS_CAR_1                  = 72.65 37.40 33.10
SETTING_MINS_CAR_2                  = -101.14 -43.68 -22.70
SETTING_MAXS_CAR_2                  = 80.45 38.01 38.10
SETTING_MINS_CAR_3                  = -112.95 -43.41 -24.82
SETTING_MAXS_CAR_3                  = 88.61 42.03 34.79

SETTING_CAR_LOAD                    = 1             # Whether to load saved Car Traps data of the current map
SETTING_CAR_CHECK                   = 10.0          # Maximum selection distance when checking nearby Car Traps
SETTING_CAR_TASK                    = 0.1           # Time interval in seconds to check for Car Traps and apply their effects
SETTING_OFFSET_BASE                 = 120.0         # Default forward offset when previewing Car Trap placement
SETTING_OFFSET                      = 65.0 900.0    # Default minimum and maximum offset from the player to the Car Trap (MIN MAX)
SETTING_OFFSET_STEP                 = 10.0          # Step size when scrolling to move Car Trap forward/backward
SETTING_GHOST_ALPHA                 = 120           # Transparency level of the ghost preview model (0 - 255)
SETTING_ROTATION_STEP               = 22.5          # Step size when rotating the Car Trap

[Default]

[Slow Car]
CAR_FALL_STRENGTH   = 32.0 35.0

[Fast Car]
CAR_FALL_STRENGTH   = 164.0 192.0

[Terrorist]
CAR_TEAM            = 1

[Counter-Terrorist]
CAR_TEAM            = 2

